"""Canonical group/sub intent labels for CEP (flat leaf = group/sub)."""

from __future__ import annotations

# Top-level groups (inbox filters)
GROUPS = (
    "pre_purchase",
    "order",
    "post_purchase",
    "noise",
)

# Leaf labels predicted by the model (group/sub)
INTENTS = (
    # pre_purchase
    "pre_purchase/product",
    "pre_purchase/price",
    "pre_purchase/shipping",
    "pre_purchase/other",
    # order
    "order/status",
    "order/change",
    "order/payment",
    "order/other",
    # post_purchase
    "post_purchase/delivery",
    "post_purchase/return",
    "post_purchase/feedback",
    "post_purchase/other",
    # noise
    "noise/thanks",
    "noise/greeting",
    "noise/human",
    "noise/spam",
)

INTENT_DESCRIPTIONS: dict[str, str] = {
    "pre_purchase/product": "Product info, stock, size, colours, how it works",
    "pre_purchase/price": "Price, discount, offer, COD availability",
    "pre_purchase/shipping": "Shipping cost / ETA before buying",
    "pre_purchase/other": "Other pre-purchase questions",
    "order/status": "Where is my order, tracking, delayed shipment",
    "order/change": "Cancel order or edit address/items",
    "order/payment": "Payment failed, invoice, charged twice",
    "order/other": "Other questions about an existing order",
    "post_purchase/delivery": "Damaged, wrong, missing, lost, not received",
    "post_purchase/return": "Return, refund, exchange",
    "post_purchase/feedback": "Review, complaint, compliment about experience",
    "post_purchase/other": "Warranty / misc after purchase",
    "noise/thanks": "ok / thanks / 👍 only",
    "noise/greeting": "hi / hello only",
    "noise/human": "Wants to talk to a human agent",
    "noise/spam": "Junk, unrelated, empty chatter",
}


def split_label(label: str) -> tuple[str, str]:
    if "/" in label:
        group, sub = label.split("/", 1)
        return group, sub
    return label, "other"


def is_intent(label: str) -> bool:
    return label in INTENTS


# Bitext retail intent → leaf
BITEXT_TO_INTENT: dict[str, str] = {
    "product_information": "pre_purchase/product",
    "availability": "pre_purchase/product",
    "availability_online": "pre_purchase/product",
    "availability_in_store": "pre_purchase/product",
    "add_product": "pre_purchase/product",
    "remove_product": "pre_purchase/product",
    "payment_methods": "pre_purchase/price",
    "pay": "pre_purchase/price",
    "shipping_costs": "pre_purchase/shipping",
    "submit_product_idea": "pre_purchase/other",
    "track_order": "order/status",
    "track_delivery": "order/status",
    "delivery_time": "pre_purchase/shipping",
    "order_history": "order/status",
    "request_invoice": "order/payment",
    "cancel_order": "order/change",
    "change_order": "order/change",
    "payment_issue": "order/payment",
    "delivery_issue": "post_purchase/delivery",
    "damaged_delivery": "post_purchase/delivery",
    "missing_item": "post_purchase/delivery",
    "wrong_item": "post_purchase/delivery",
    "product_issue": "post_purchase/delivery",
    "exchange_product": "post_purchase/return",
    "exchange_product_in_store": "post_purchase/return",
    "return_product": "post_purchase/return",
    "return_product_online": "post_purchase/return",
    "return_product_in_store": "post_purchase/return",
    "return_policy": "post_purchase/return",
    "refund_policy": "post_purchase/return",
    "refund_status": "post_purchase/return",
    "request_refund": "post_purchase/return",
    "submit_feedback": "post_purchase/feedback",
    "submit_product_feedback": "post_purchase/feedback",
    "technical_issue": "post_purchase/other",
    "customer_service": "post_purchase/other",
    "human_agent": "noise/human",
}

# Hinglish retail dataset → leaf
HINGLISH_TO_INTENT: dict[str, str] = {
    "product_availability": "pre_purchase/product",
    "product_information": "pre_purchase/product",
    "discount_query": "pre_purchase/price",
    "track_order": "order/status",
    "cancel_order": "order/change",
    "exchange_product": "post_purchase/return",
    "refund_status": "post_purchase/return",
    "delivery_complaint": "post_purchase/delivery",
    "damaged_item": "post_purchase/delivery",
    "wrong_item": "post_purchase/delivery",
    "return_request": "post_purchase/return",
    "payment_issue": "order/payment",
    "other": "noise/spam",
}

# Synthetic EN + Hinglish examples per leaf (boost accuracy on Indian support chat)
SYNTHETIC: dict[str, list[str]] = {
    "pre_purchase/product": [
        "Do you have this in size M?",
        "Is this available in black?",
        "Stock available hai kya?",
        "Size chart share karo",
        "Material kya hai?",
        "Is this waterproof?",
        "Compatible with iPhone 15?",
        "Do you have other colours?",
        "When will this be back in stock?",
        "Ye product original hai kya?",
        "Can I order 2 pieces?",
        "Looking to buy, need recommendation",
        "Product details please",
        "Is XL available?",
        "Colour options batao",
    ],
    "pre_purchase/price": [
        "What is the price of this product?",
        "Kitne ka hai ye?",
        "Any discount on this?",
        "Is COD available?",
        "COD hai kya?",
        "Best price mil sakta hai?",
        "Offer chal raha hai kya?",
        "How much does this cost?",
        "Price after discount?",
        "Coupon code hai?",
    ],
    "pre_purchase/shipping": [
        "Do you ship to Bangalore?",
        "Delivery charges kitne hain before order?",
        "Shipping cost kya hai?",
        "How many days for delivery if I order?",
        "Free shipping hai kya?",
        "Pan India deliver karte ho?",
        "Delivery time before I buy?",
    ],
    "pre_purchase/other": [
        "Can I gift wrap this?",
        "Do you have a physical store?",
        "Warranty period before purchase?",
        "Bulk order possible?",
        "Reseller kaise banaye?",
    ],
    "order/status": [
        "Where is my order?",
        "Track my shipment",
        "Order kab deliver hoga?",
        "Tracking link bhejo",
        "Still not delivered, status?",
        "AWB number se track karo",
        "Expected delivery date?",
        "Courier ne pick up kiya kya?",
        "My order is delayed",
        "Out for delivery hai kya?",
        "Order status batao",
        "Mere order ka tracking?",
        "Shipment kahan pe hai?",
        "When will my package arrive?",
    ],
    "order/change": [
        "Please cancel my order",
        "Order cancel kar do",
        "Change my delivery address",
        "Address change karna hai",
        "Remove one item from my order",
        "I ordered wrong size, can I change?",
        "Update shipping address before it ships",
        "Mera order edit karo",
    ],
    "order/payment": [
        "Payment failed but money deducted",
        "Invoice bhejo please",
        "I was charged twice",
        "Payment nahi hua order place?",
        "Need GST invoice for my order",
        "Refund of failed payment?",
        "UPI payment stuck",
    ],
    "order/other": [
        "Can I add a gift note to my order?",
        "Order confirmation email nahi aaya",
        "Who is the courier for my order?",
    ],
    "post_purchase/delivery": [
        "My package arrived damaged",
        "Wrong item received",
        "Item missing from the box",
        "Parcel lost in transit",
        "Order deliver nahi hua",
        "Product toot gaya delivery mein",
        "Galat size aaya",
        "Box empty tha",
        "Never received my order",
        "Damaged product mila",
    ],
    "post_purchase/return": [
        "I want to return this product",
        "Return request raise karo",
        "Need a refund",
        "Refund status kya hai?",
        "Exchange for another size",
        "Return pickup kab aayega?",
        "Money back kab milega?",
        "Want to exchange this item",
    ],
    "post_purchase/feedback": [
        "Great service, thank you so much for help",
        "Very bad experience with delivery agent",
        "Product quality is excellent",
        "Your support team was rude",
        "Feedback: packaging was poor",
        "Loved the product, will order again",
        "Complaint about late reply from support",
    ],
    "post_purchase/other": [
        "How do I claim warranty?",
        "Product stopped working after a week",
        "Need help setting up the product I bought",
        "Warranty card missing",
    ],
    "noise/thanks": [
        "ok",
        "okay",
        "thanks",
        "thank you",
        "thx",
        "👍",
        "🙏",
        "ok bro",
        "done",
        "noted",
        "thanks a lot",
        "shukriya",
        "dhanyavad",
        "cool",
        "nice",
        "👍 ok",
    ],
    "noise/greeting": [
        "hi",
        "hello",
        "hey",
        "hii",
        "good morning",
        "good evening",
        "namaste",
        "hola",
    ],
    "noise/human": [
        "I want to talk to a human",
        "Connect me to an agent",
        "Agent se baat karni hai",
        "Please transfer to customer care executive",
        "Don't want bot, real person please",
        "Human agent chahiye",
    ],
    "noise/spam": [
        "lol",
        "haha",
        "???",
        "...",
        "test",
        "testing",
        "asdf",
        "spam offer click here free iphone",
        "Congratulations you won a lottery prize claim now",
        "Buy followers cheap!!!",
        "Unsubscribe me",
        "Sticker",
        "Photo",
        "Voice message",
        "Unsupported message type",
        "k",
        "kk",
        "hmm",
        "yes",
        "no",
        "haan",
        "nahi",
    ],
}
